services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ambrosia-app
    restart: unless-stopped
    ports:
      - '80:80'
      - '5173:5173'
    volumes:
      - ./:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    networks:
      - ambrosia-network

networks:
  ambrosia-network:
    driver: bridge
